In [3]:
import numpy as np
lst=[10,20,30,40,50,60]
print(lst,type(lst))
ndo=np.array(lst)
print("content of ndo",ndo)
print("type of ndo",type(ndo))
print("dtype od ndo",ndo.dtype)
print("Dimension",ndo.ndim)
print("shape",ndo.shape)
print("size",ndo.size)

[10, 20, 30, 40, 50, 60] <class 'list'>
content of ndo [10 20 30 40 50 60]
type of ndo <class 'numpy.ndarray'>
dtype od ndo int32
Dimension 1
shape (6,)
size 6


In [3]:
import numpy as np
lst=[10,20,30,40,50,60]
print(lst,type(lst))
ndo=np.array(lst)
print("content of ndo",ndo)
print("type of ndo",type(ndo))
print("dtype od ndo",ndo.dtype)
print("Dimension",ndo.ndim)
print("shape",ndo.shape)
print("size",ndo.size)

[10, 20, 30, 40, 50, 60] <class 'list'>
content of ndo [10 20 30 40 50 60]
type of ndo <class 'numpy.ndarray'>
dtype od ndo int32
Dimension 1
shape (6,)
size 6


In [4]:
import numpy as np
lst=[[10,20],[30,40],[50,60]]
print(lst,type(lst))
ndo=np.array(lst)
print(ndo)

[[10, 20], [30, 40], [50, 60]] <class 'list'>
[[10 20]
 [30 40]
 [50 60]]


In [6]:
#vector based operation
import numpy as np
lst=[1,2,3,4,5]
#list=lst+1//type error
ndo=np.array(lst)
result=ndo+1
print(result)

[2 3 4 5 6]


In [12]:
#reshape()
import numpy as np
lst=[1,2,3,4,5,6,7,8,9,10,11,12]
ndo=np.array(lst)
print(ndo)
print("Type",type(ndo))
print("dimension",ndo.ndim)
print("Dtype",ndo.dtype)
print("shape",ndo.shape)
print("size",ndo.size)
print("*"*25)
print("2D")
ndo=ndo.reshape(3,4)
print(ndo)
print("Type",type(ndo))
print("dimension",ndo.ndim)
print("Dtype",ndo.dtype)
print("shape",ndo.shape)
print("size",ndo.size)
print("*"*25)
print("2D")

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Type <class 'numpy.ndarray'>
dimension 1
Dtype int32
shape (12,)
size 12
*************************
2D
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Type <class 'numpy.ndarray'>
dimension 2
Dtype int32
shape (3, 4)
size 12
*************************
2D


In [13]:
#create nd array obeject using arange()
import numpy as np
ndo=np.arange(12)
ndo=ndo.reshape(4,3)
print (ndo)
print("Type",type(ndo))
print("Dimension",ndo.ndim)
print("Dtype",ndo.dtype)
print("shape",ndo.shape)
print("size",ndo.size)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Type <class 'numpy.ndarray'>
Dimension 2
Dtype int32
shape (4, 3)
size 12


In [15]:
import numpy as np
ndo=np.zeros((2,3),dtype=int)
print(ndo)

[[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
ndo=np.onces((3,3),dtype)